// <auto-generated />
namespace OnlineMobileRechargeSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ActivePlanModify1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActivePlanModify1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110051206438_ActivePlanModify1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
